export const SET_DRINKERS = "SET_DRINKERS";
export const SET_QUERY = "SET_QUERY";
export const SET_LOADING_QUERY = "SET_LOADING_QUERY";
export const SET_LOADING_DRINKER = "SET_LOADING_DRINKER";
export const GET_ERRORS = "GET_ERRORS";
